name: Unzip Files

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unzip files
      run: |
        sudo apt-get install unzip
        unzip startbootstrap-sb-admin-2-gh-pages.zip -d .github/

    - name: Commit unzipped files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Unzipped files"
        git push
        
